// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item;
using IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Thumbnails;
using IcePanel.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams
{
    /// <summary>
    /// Builds and executes requests for operations under \landscapes\{landscapeId}\versions\{versionId}\diagrams
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DiagramsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The thumbnails property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Thumbnails.ThumbnailsRequestBuilder Thumbnails
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Thumbnails.ThumbnailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the IcePanel.Api.landscapes.item.versions.item.diagrams.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.WithDiagramItemRequestBuilder"/></returns>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.WithDiagramItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("diagramId", position);
                return new global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.WithDiagramItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiagramsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/diagrams{?filter*,updateViewedAt*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiagramsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/diagrams{?filter*,updateViewedAt*}", rawUrl)
        {
        }
        /// <summary>
        /// List
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsGetResponse?> GetAsDiagramsGetResponseAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsGetResponse> GetAsDiagramsGetResponseAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsGetResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsDiagramsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse?> GetAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse> GetAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostResponse?> PostAsDiagramsPostResponseAsync(global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostRequestBody body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostResponse> PostAsDiagramsPostResponseAsync(global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostRequestBody body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsDiagramsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse?> PostAsync(global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostRequestBody body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse> PostAsync(global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostRequestBody body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostRequestBody body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsPostRequestBody body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiagramsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiagramsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Create
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiagramsRequestBuilderPostQueryParameters 
        {
            [QueryParameter("updateViewedAt")]
            public bool? UpdateViewedAt { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiagramsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.DiagramsRequestBuilder.DiagramsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
