// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Models;
using IcePanel.Api.Organizations.Item.Teams.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IcePanel.Api.Organizations.Item.Teams
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{organizationId}\teams
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TeamsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the IcePanel.Api.organizations.item.teams.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IcePanel.Api.Organizations.Item.Teams.Item.WithTeamItemRequestBuilder"/></returns>
        public global::IcePanel.Api.Organizations.Item.Teams.Item.WithTeamItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("teamId", position);
                return new global::IcePanel.Api.Organizations.Item.Teams.Item.WithTeamItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Organizations.Item.Teams.TeamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organizationId}/teams", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Organizations.Item.Teams.TeamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organizationId}/teams", rawUrl)
        {
        }
        /// <summary>
        /// List
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Organizations.Item.Teams.TeamsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Organizations.Item.Teams.TeamsGetResponse?> GetAsTeamsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Organizations.Item.Teams.TeamsGetResponse> GetAsTeamsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Organizations.Item.Teams.TeamsGetResponse>(requestInfo, global::IcePanel.Api.Organizations.Item.Teams.TeamsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsTeamsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse>(requestInfo, global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Organizations.Item.Teams.TeamsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Organizations.Item.Teams.TeamsPostResponse?> PostAsTeamsPostResponseAsync(global::IcePanel.Api.Models.TeamRequired body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Organizations.Item.Teams.TeamsPostResponse> PostAsTeamsPostResponseAsync(global::IcePanel.Api.Models.TeamRequired body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Organizations.Item.Teams.TeamsPostResponse>(requestInfo, global::IcePanel.Api.Organizations.Item.Teams.TeamsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsTeamsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse?> PostAsync(global::IcePanel.Api.Models.TeamRequired body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse> PostAsync(global::IcePanel.Api.Models.TeamRequired body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse>(requestInfo, global::IcePanel.Api.Organizations.Item.Teams.TeamsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::IcePanel.Api.Models.TeamRequired body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::IcePanel.Api.Models.TeamRequired body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Organizations.Item.Teams.TeamsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IcePanel.Api.Organizations.Item.Teams.TeamsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IcePanel.Api.Organizations.Item.Teams.TeamsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TeamsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TeamsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
