// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActionDiagramContentCreate_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "diagram-content-create")]
        #pragma warning disable CS1591
        DiagramContentCreate,
        #pragma warning restore CS1591
    }
}
