// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActionTagGroupCreate_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "tag-group-create")]
        #pragma warning disable CS1591
        TagGroupCreate,
        #pragma warning restore CS1591
    }
}
