// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>
    /// A Component describes a software component. It is typically intimately linked to the source code that constitutes the component, and should be what a developer may regard a &quot;unit of software&quot;, usually with a distinct deployable or linkable artifact.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BackstageComponent : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The apiVersion property</summary>
        public global::IcePanel.Api.Models.BackstageComponent_apiVersion? ApiVersion { get; set; }
        /// <summary>The kind property</summary>
        public global::IcePanel.Api.Models.BackstageComponent_kind? Kind { get; set; }
        /// <summary>Metadata fields common to all versions/kinds of entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.BackstageEntityMeta? Metadata { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.BackstageEntityMeta Metadata { get; set; }
#endif
        /// <summary>The relations that this entity has with other entities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IcePanel.Api.Models.BackstageRelation>? Relations { get; set; }
#nullable restore
#else
        public List<global::IcePanel.Api.Models.BackstageRelation> Relations { get; set; }
#endif
        /// <summary>The spec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.BackstageComponent_spec? Spec { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.BackstageComponent_spec Spec { get; set; }
#endif
        /// <summary>The current status of the entity, as claimed by various sources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.BackstageStatus? Status { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.BackstageStatus Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.BackstageComponent"/> and sets the default values.
        /// </summary>
        public BackstageComponent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.BackstageComponent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.BackstageComponent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.BackstageComponent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apiVersion", n => { ApiVersion = n.GetEnumValue<global::IcePanel.Api.Models.BackstageComponent_apiVersion>(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::IcePanel.Api.Models.BackstageComponent_kind>(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::IcePanel.Api.Models.BackstageEntityMeta>(global::IcePanel.Api.Models.BackstageEntityMeta.CreateFromDiscriminatorValue); } },
                { "relations", n => { Relations = n.GetCollectionOfObjectValues<global::IcePanel.Api.Models.BackstageRelation>(global::IcePanel.Api.Models.BackstageRelation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "spec", n => { Spec = n.GetObjectValue<global::IcePanel.Api.Models.BackstageComponent_spec>(global::IcePanel.Api.Models.BackstageComponent_spec.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::IcePanel.Api.Models.BackstageStatus>(global::IcePanel.Api.Models.BackstageStatus.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::IcePanel.Api.Models.BackstageComponent_apiVersion>("apiVersion", ApiVersion);
            writer.WriteEnumValue<global::IcePanel.Api.Models.BackstageComponent_kind>("kind", Kind);
            writer.WriteObjectValue<global::IcePanel.Api.Models.BackstageEntityMeta>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::IcePanel.Api.Models.BackstageRelation>("relations", Relations);
            writer.WriteObjectValue<global::IcePanel.Api.Models.BackstageComponent_spec>("spec", Spec);
            writer.WriteObjectValue<global::IcePanel.Api.Models.BackstageStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
