// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CatalogSuggestionBrandLogoFormat : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates if the file has a transparent background.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Background { get; set; }
#nullable restore
#else
        public string Background { get; set; }
#endif
        /// <summary>File format of the logo</summary>
        public global::IcePanel.Api.Models.CatalogSuggestionBrandLogoFormat_format? Format { get; set; }
        /// <summary>Height of the logo in pixels</summary>
        public double? Height { get; set; }
        /// <summary>File size in bytes</summary>
        public double? Size { get; set; }
        /// <summary>File source url of the logo</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Src { get; set; }
#nullable restore
#else
        public string Src { get; set; }
#endif
        /// <summary>Width of the logo in pixels</summary>
        public double? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.CatalogSuggestionBrandLogoFormat"/> and sets the default values.
        /// </summary>
        public CatalogSuggestionBrandLogoFormat()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.CatalogSuggestionBrandLogoFormat"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.CatalogSuggestionBrandLogoFormat CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.CatalogSuggestionBrandLogoFormat();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "background", n => { Background = n.GetStringValue(); } },
                { "format", n => { Format = n.GetEnumValue<global::IcePanel.Api.Models.CatalogSuggestionBrandLogoFormat_format>(); } },
                { "height", n => { Height = n.GetDoubleValue(); } },
                { "size", n => { Size = n.GetDoubleValue(); } },
                { "src", n => { Src = n.GetStringValue(); } },
                { "width", n => { Width = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("background", Background);
            writer.WriteEnumValue<global::IcePanel.Api.Models.CatalogSuggestionBrandLogoFormat_format>("format", Format);
            writer.WriteDoubleValue("height", Height);
            writer.WriteDoubleValue("size", Size);
            writer.WriteStringValue("src", Src);
            writer.WriteDoubleValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
