// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>Type or category of technology</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CatalogTechnologyTypeNullable
    {
        [EnumMember(Value = "data-storage")]
        #pragma warning disable CS1591
        DataStorage,
        #pragma warning restore CS1591
        [EnumMember(Value = "deployment")]
        #pragma warning disable CS1591
        Deployment,
        #pragma warning restore CS1591
        [EnumMember(Value = "framework-library")]
        #pragma warning disable CS1591
        FrameworkLibrary,
        #pragma warning restore CS1591
        [EnumMember(Value = "gateway")]
        #pragma warning disable CS1591
        Gateway,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "language")]
        #pragma warning disable CS1591
        Language,
        #pragma warning restore CS1591
        [EnumMember(Value = "message-broker")]
        #pragma warning disable CS1591
        MessageBroker,
        #pragma warning restore CS1591
        [EnumMember(Value = "network")]
        #pragma warning disable CS1591
        Network,
        #pragma warning restore CS1591
        [EnumMember(Value = "protocol")]
        #pragma warning disable CS1591
        Protocol,
        #pragma warning restore CS1591
        [EnumMember(Value = "runtime")]
        #pragma warning disable CS1591
        Runtime,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-tool")]
        #pragma warning disable CS1591
        ServiceTool,
        #pragma warning restore CS1591
    }
}
