// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DiagramContentRequired : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DiagramContentRequired_comments? Comments { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DiagramContentRequired_comments Comments { get; set; }
#endif
        /// <summary>The commit property</summary>
        public double? Commit { get; set; }
        /// <summary>The connections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DiagramContentRequired_connections? Connections { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DiagramContentRequired_connections Connections { get; set; }
#endif
        /// <summary>The objects property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DiagramContentRequired_objects? Objects { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DiagramContentRequired_objects Objects { get; set; }
#endif
        /// <summary>The tasksProposed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IcePanel.Api.Models.TaskObject>? TasksProposed { get; set; }
#nullable restore
#else
        public List<global::IcePanel.Api.Models.TaskObject> TasksProposed { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.DiagramContentRequired"/> and sets the default values.
        /// </summary>
        public DiagramContentRequired()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.DiagramContentRequired"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.DiagramContentRequired CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.DiagramContentRequired();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comments", n => { Comments = n.GetObjectValue<global::IcePanel.Api.Models.DiagramContentRequired_comments>(global::IcePanel.Api.Models.DiagramContentRequired_comments.CreateFromDiscriminatorValue); } },
                { "commit", n => { Commit = n.GetDoubleValue(); } },
                { "connections", n => { Connections = n.GetObjectValue<global::IcePanel.Api.Models.DiagramContentRequired_connections>(global::IcePanel.Api.Models.DiagramContentRequired_connections.CreateFromDiscriminatorValue); } },
                { "objects", n => { Objects = n.GetObjectValue<global::IcePanel.Api.Models.DiagramContentRequired_objects>(global::IcePanel.Api.Models.DiagramContentRequired_objects.CreateFromDiscriminatorValue); } },
                { "tasksProposed", n => { TasksProposed = n.GetCollectionOfObjectValues<global::IcePanel.Api.Models.TaskObject>(global::IcePanel.Api.Models.TaskObject.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::IcePanel.Api.Models.DiagramContentRequired_comments>("comments", Comments);
            writer.WriteDoubleValue("commit", Commit);
            writer.WriteObjectValue<global::IcePanel.Api.Models.DiagramContentRequired_connections>("connections", Connections);
            writer.WriteObjectValue<global::IcePanel.Api.Models.DiagramContentRequired_objects>("objects", Objects);
            writer.WriteCollectionOfObjectValues<global::IcePanel.Api.Models.TaskObject>("tasksProposed", TasksProposed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
