// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember1"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember10"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember11"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember12"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember13"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember14"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember15"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember16"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember17"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember18"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember19"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember2"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember20"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember21"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember22"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember3"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember4"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember5"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember6"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember7"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember8"/>, <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember9"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DraftTaskRequired : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember1? DraftTaskRequiredMember1 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember1 DraftTaskRequiredMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember10? DraftTaskRequiredMember10 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember10 DraftTaskRequiredMember10 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember11"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember11? DraftTaskRequiredMember11 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember11 DraftTaskRequiredMember11 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember12"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember12? DraftTaskRequiredMember12 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember12 DraftTaskRequiredMember12 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember13"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember13? DraftTaskRequiredMember13 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember13 DraftTaskRequiredMember13 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember14"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember14? DraftTaskRequiredMember14 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember14 DraftTaskRequiredMember14 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember15"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember15? DraftTaskRequiredMember15 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember15 DraftTaskRequiredMember15 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember16"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember16? DraftTaskRequiredMember16 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember16 DraftTaskRequiredMember16 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember17"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember17? DraftTaskRequiredMember17 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember17 DraftTaskRequiredMember17 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember18"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember18? DraftTaskRequiredMember18 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember18 DraftTaskRequiredMember18 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember19"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember19? DraftTaskRequiredMember19 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember19 DraftTaskRequiredMember19 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember2? DraftTaskRequiredMember2 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember2 DraftTaskRequiredMember2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember20"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember20? DraftTaskRequiredMember20 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember20 DraftTaskRequiredMember20 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember21"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember21? DraftTaskRequiredMember21 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember21 DraftTaskRequiredMember21 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember22"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember22? DraftTaskRequiredMember22 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember22 DraftTaskRequiredMember22 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember3? DraftTaskRequiredMember3 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember3 DraftTaskRequiredMember3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember4? DraftTaskRequiredMember4 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember4 DraftTaskRequiredMember4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember5? DraftTaskRequiredMember5 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember5 DraftTaskRequiredMember5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember6? DraftTaskRequiredMember6 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember6 DraftTaskRequiredMember6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember7? DraftTaskRequiredMember7 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember7 DraftTaskRequiredMember7 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember8? DraftTaskRequiredMember8 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember8 DraftTaskRequiredMember8 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.DraftTaskRequiredMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.DraftTaskRequiredMember9? DraftTaskRequiredMember9 { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.DraftTaskRequiredMember9 DraftTaskRequiredMember9 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.DraftTaskRequired"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.DraftTaskRequired CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::IcePanel.Api.Models.DraftTaskRequired();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember1 = new global::IcePanel.Api.Models.DraftTaskRequiredMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember10 = new global::IcePanel.Api.Models.DraftTaskRequiredMember10();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember11 = new global::IcePanel.Api.Models.DraftTaskRequiredMember11();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember12 = new global::IcePanel.Api.Models.DraftTaskRequiredMember12();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember13 = new global::IcePanel.Api.Models.DraftTaskRequiredMember13();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember14 = new global::IcePanel.Api.Models.DraftTaskRequiredMember14();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember15 = new global::IcePanel.Api.Models.DraftTaskRequiredMember15();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember16 = new global::IcePanel.Api.Models.DraftTaskRequiredMember16();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember17 = new global::IcePanel.Api.Models.DraftTaskRequiredMember17();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember18 = new global::IcePanel.Api.Models.DraftTaskRequiredMember18();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember19 = new global::IcePanel.Api.Models.DraftTaskRequiredMember19();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember2 = new global::IcePanel.Api.Models.DraftTaskRequiredMember2();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember20 = new global::IcePanel.Api.Models.DraftTaskRequiredMember20();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember21 = new global::IcePanel.Api.Models.DraftTaskRequiredMember21();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember22 = new global::IcePanel.Api.Models.DraftTaskRequiredMember22();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember3 = new global::IcePanel.Api.Models.DraftTaskRequiredMember3();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember4 = new global::IcePanel.Api.Models.DraftTaskRequiredMember4();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember5 = new global::IcePanel.Api.Models.DraftTaskRequiredMember5();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember6 = new global::IcePanel.Api.Models.DraftTaskRequiredMember6();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember7 = new global::IcePanel.Api.Models.DraftTaskRequiredMember7();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember8 = new global::IcePanel.Api.Models.DraftTaskRequiredMember8();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DraftTaskRequiredMember9 = new global::IcePanel.Api.Models.DraftTaskRequiredMember9();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DraftTaskRequiredMember1 != null)
            {
                return DraftTaskRequiredMember1.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember10 != null)
            {
                return DraftTaskRequiredMember10.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember11 != null)
            {
                return DraftTaskRequiredMember11.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember12 != null)
            {
                return DraftTaskRequiredMember12.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember13 != null)
            {
                return DraftTaskRequiredMember13.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember14 != null)
            {
                return DraftTaskRequiredMember14.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember15 != null)
            {
                return DraftTaskRequiredMember15.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember16 != null)
            {
                return DraftTaskRequiredMember16.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember17 != null)
            {
                return DraftTaskRequiredMember17.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember18 != null)
            {
                return DraftTaskRequiredMember18.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember19 != null)
            {
                return DraftTaskRequiredMember19.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember2 != null)
            {
                return DraftTaskRequiredMember2.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember20 != null)
            {
                return DraftTaskRequiredMember20.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember21 != null)
            {
                return DraftTaskRequiredMember21.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember22 != null)
            {
                return DraftTaskRequiredMember22.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember3 != null)
            {
                return DraftTaskRequiredMember3.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember4 != null)
            {
                return DraftTaskRequiredMember4.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember5 != null)
            {
                return DraftTaskRequiredMember5.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember6 != null)
            {
                return DraftTaskRequiredMember6.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember7 != null)
            {
                return DraftTaskRequiredMember7.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember8 != null)
            {
                return DraftTaskRequiredMember8.GetFieldDeserializers();
            }
            else if(DraftTaskRequiredMember9 != null)
            {
                return DraftTaskRequiredMember9.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DraftTaskRequiredMember1 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember1>(null, DraftTaskRequiredMember1);
            }
            else if(DraftTaskRequiredMember10 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember10>(null, DraftTaskRequiredMember10);
            }
            else if(DraftTaskRequiredMember11 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember11>(null, DraftTaskRequiredMember11);
            }
            else if(DraftTaskRequiredMember12 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember12>(null, DraftTaskRequiredMember12);
            }
            else if(DraftTaskRequiredMember13 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember13>(null, DraftTaskRequiredMember13);
            }
            else if(DraftTaskRequiredMember14 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember14>(null, DraftTaskRequiredMember14);
            }
            else if(DraftTaskRequiredMember15 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember15>(null, DraftTaskRequiredMember15);
            }
            else if(DraftTaskRequiredMember16 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember16>(null, DraftTaskRequiredMember16);
            }
            else if(DraftTaskRequiredMember17 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember17>(null, DraftTaskRequiredMember17);
            }
            else if(DraftTaskRequiredMember18 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember18>(null, DraftTaskRequiredMember18);
            }
            else if(DraftTaskRequiredMember19 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember19>(null, DraftTaskRequiredMember19);
            }
            else if(DraftTaskRequiredMember2 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember2>(null, DraftTaskRequiredMember2);
            }
            else if(DraftTaskRequiredMember20 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember20>(null, DraftTaskRequiredMember20);
            }
            else if(DraftTaskRequiredMember21 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember21>(null, DraftTaskRequiredMember21);
            }
            else if(DraftTaskRequiredMember22 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember22>(null, DraftTaskRequiredMember22);
            }
            else if(DraftTaskRequiredMember3 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember3>(null, DraftTaskRequiredMember3);
            }
            else if(DraftTaskRequiredMember4 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember4>(null, DraftTaskRequiredMember4);
            }
            else if(DraftTaskRequiredMember5 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember5>(null, DraftTaskRequiredMember5);
            }
            else if(DraftTaskRequiredMember6 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember6>(null, DraftTaskRequiredMember6);
            }
            else if(DraftTaskRequiredMember7 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember7>(null, DraftTaskRequiredMember7);
            }
            else if(DraftTaskRequiredMember8 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember8>(null, DraftTaskRequiredMember8);
            }
            else if(DraftTaskRequiredMember9 != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.DraftTaskRequiredMember9>(null, DraftTaskRequiredMember9);
            }
        }
    }
}
#pragma warning restore CS0618
