// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GithubInstall : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The createdBy property</summary>
        public global::IcePanel.Api.Models.AuthType? CreatedBy { get; set; }
        /// <summary>The createdById property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedById { get; set; }
#nullable restore
#else
        public string CreatedById { get; set; }
#endif
        /// <summary>The githubId property</summary>
        public double? GithubId { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The organizationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The ownerId property</summary>
        public double? OwnerId { get; set; }
        /// <summary>The ownerLogin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerLogin { get; set; }
#nullable restore
#else
        public string OwnerLogin { get; set; }
#endif
        /// <summary>The ownerType property</summary>
        public global::IcePanel.Api.Models.GithubInstallType? OwnerType { get; set; }
        /// <summary>The senderId property</summary>
        public double? SenderId { get; set; }
        /// <summary>The senderLogin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderLogin { get; set; }
#nullable restore
#else
        public string SenderLogin { get; set; }
#endif
        /// <summary>The senderType property</summary>
        public global::IcePanel.Api.Models.GithubInstallType? SenderType { get; set; }
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.GithubInstall"/> and sets the default values.
        /// </summary>
        public GithubInstall()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.GithubInstall"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.GithubInstall CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.GithubInstall();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetEnumValue<global::IcePanel.Api.Models.AuthType>(); } },
                { "createdById", n => { CreatedById = n.GetStringValue(); } },
                { "githubId", n => { GithubId = n.GetDoubleValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "organizationId", n => { OrganizationId = n.GetStringValue(); } },
                { "ownerId", n => { OwnerId = n.GetDoubleValue(); } },
                { "ownerLogin", n => { OwnerLogin = n.GetStringValue(); } },
                { "ownerType", n => { OwnerType = n.GetEnumValue<global::IcePanel.Api.Models.GithubInstallType>(); } },
                { "senderId", n => { SenderId = n.GetDoubleValue(); } },
                { "senderLogin", n => { SenderLogin = n.GetStringValue(); } },
                { "senderType", n => { SenderType = n.GetEnumValue<global::IcePanel.Api.Models.GithubInstallType>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteEnumValue<global::IcePanel.Api.Models.AuthType>("createdBy", CreatedBy);
            writer.WriteStringValue("createdById", CreatedById);
            writer.WriteDoubleValue("githubId", GithubId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("organizationId", OrganizationId);
            writer.WriteDoubleValue("ownerId", OwnerId);
            writer.WriteStringValue("ownerLogin", OwnerLogin);
            writer.WriteEnumValue<global::IcePanel.Api.Models.GithubInstallType>("ownerType", OwnerType);
            writer.WriteDoubleValue("senderId", SenderId);
            writer.WriteStringValue("senderLogin", SenderLogin);
            writer.WriteEnumValue<global::IcePanel.Api.Models.GithubInstallType>("senderType", SenderType);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
