// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ModelObjectRequired : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Short summary of the object shown as the display description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Caption { get; set; }
#nullable restore
#else
        public string Caption { get; set; }
#endif
        /// <summary>The commit property</summary>
        public double? Commit { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The domainId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DomainId { get; set; }
#nullable restore
#else
        public string DomainId { get; set; }
#endif
        /// <summary>The external property</summary>
        public bool? External { get; set; }
        /// <summary>IDs of the groups this model object belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? GroupIds { get; set; }
#nullable restore
#else
        public List<string> GroupIds { get; set; }
#endif
        /// <summary>The handleId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HandleId { get; set; }
#nullable restore
#else
        public string HandleId { get; set; }
#endif
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.Objects? Icon { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.Objects Icon { get; set; }
#endif
        /// <summary>Generic key value store used for creating custom integrations</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.ModelObjectRequired_labels? Labels { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.ModelObjectRequired_labels Labels { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.ModelObjectRequired_links? Links { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.ModelObjectRequired_links Links { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Parent model object ID, null for the root level model object</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentId { get; set; }
#nullable restore
#else
        public string ParentId { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::IcePanel.Api.Models.ModelObjectStatus? Status { get; set; }
        /// <summary>The tagIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TagIds { get; set; }
#nullable restore
#else
        public List<string> TagIds { get; set; }
#endif
        /// <summary>Team IDs that own this model object, does not propergate up or down</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TeamIds { get; set; }
#nullable restore
#else
        public List<string> TeamIds { get; set; }
#endif
        /// <summary>Model object (+child diagram, diagram groups and flows) can only be edited by owners and admins</summary>
        public bool? TeamOnlyEditing { get; set; }
        /// <summary>Catalog technology IDs assigned to this model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TechnologyIds { get; set; }
#nullable restore
#else
        public List<string> TechnologyIds { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::IcePanel.Api.Models.ModelObjectType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.ModelObjectRequired"/> and sets the default values.
        /// </summary>
        public ModelObjectRequired()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.ModelObjectRequired"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.ModelObjectRequired CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.ModelObjectRequired();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "caption", n => { Caption = n.GetStringValue(); } },
                { "commit", n => { Commit = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "domainId", n => { DomainId = n.GetStringValue(); } },
                { "external", n => { External = n.GetBoolValue(); } },
                { "groupIds", n => { GroupIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "handleId", n => { HandleId = n.GetStringValue(); } },
                { "icon", n => { Icon = n.GetObjectValue<global::IcePanel.Api.Models.Objects>(global::IcePanel.Api.Models.Objects.CreateFromDiscriminatorValue); } },
                { "labels", n => { Labels = n.GetObjectValue<global::IcePanel.Api.Models.ModelObjectRequired_labels>(global::IcePanel.Api.Models.ModelObjectRequired_labels.CreateFromDiscriminatorValue); } },
                { "links", n => { Links = n.GetObjectValue<global::IcePanel.Api.Models.ModelObjectRequired_links>(global::IcePanel.Api.Models.ModelObjectRequired_links.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parentId", n => { ParentId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::IcePanel.Api.Models.ModelObjectStatus>(); } },
                { "tagIds", n => { TagIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "teamIds", n => { TeamIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "teamOnlyEditing", n => { TeamOnlyEditing = n.GetBoolValue(); } },
                { "technologyIds", n => { TechnologyIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::IcePanel.Api.Models.ModelObjectType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("caption", Caption);
            writer.WriteDoubleValue("commit", Commit);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("domainId", DomainId);
            writer.WriteBoolValue("external", External);
            writer.WriteCollectionOfPrimitiveValues<string>("groupIds", GroupIds);
            writer.WriteStringValue("handleId", HandleId);
            writer.WriteObjectValue<global::IcePanel.Api.Models.Objects>("icon", Icon);
            writer.WriteObjectValue<global::IcePanel.Api.Models.ModelObjectRequired_labels>("labels", Labels);
            writer.WriteObjectValue<global::IcePanel.Api.Models.ModelObjectRequired_links>("links", Links);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("parentId", ParentId);
            writer.WriteEnumValue<global::IcePanel.Api.Models.ModelObjectStatus>("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tagIds", TagIds);
            writer.WriteCollectionOfPrimitiveValues<string>("teamIds", TeamIds);
            writer.WriteBoolValue("teamOnlyEditing", TeamOnlyEditing);
            writer.WriteCollectionOfPrimitiveValues<string>("technologyIds", TechnologyIds);
            writer.WriteEnumValue<global::IcePanel.Api.Models.ModelObjectType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
