// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ModelConnectionExpandKey
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "technologies")]
        #pragma warning disable CS1591
        Technologies,
        #pragma warning restore CS1591
        [EnumMember(Value = "tags")]
        #pragma warning disable CS1591
        Tags,
        #pragma warning restore CS1591
    }
}
