// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrganizationUserInvite : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The createdBy property</summary>
        public global::IcePanel.Api.Models.AuthType? CreatedBy { get; set; }
        /// <summary>The createdById property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedById { get; set; }
#nullable restore
#else
        public string CreatedById { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The expiresAt property</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The landscapePermissions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.OrganizationUserInvite_landscapePermissions? LandscapePermissions { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.OrganizationUserInvite_landscapePermissions LandscapePermissions { get; set; }
#endif
        /// <summary>The organizationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The permission property</summary>
        public global::IcePanel.Api.Models.PermissionType? Permission { get; set; }
        /// <summary>The revokedAt property</summary>
        public DateTimeOffset? RevokedAt { get; set; }
        /// <summary>The revokedBy property</summary>
        public global::IcePanel.Api.Models.AuthType? RevokedBy { get; set; }
        /// <summary>The revokedById property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RevokedById { get; set; }
#nullable restore
#else
        public string RevokedById { get; set; }
#endif
        /// <summary>The usedAt property</summary>
        public DateTimeOffset? UsedAt { get; set; }
        /// <summary>The usedByUserId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsedByUserId { get; set; }
#nullable restore
#else
        public string UsedByUserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.OrganizationUserInvite"/> and sets the default values.
        /// </summary>
        public OrganizationUserInvite()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.OrganizationUserInvite"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.OrganizationUserInvite CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.OrganizationUserInvite();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetEnumValue<global::IcePanel.Api.Models.AuthType>(); } },
                { "createdById", n => { CreatedById = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "expiresAt", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "landscapePermissions", n => { LandscapePermissions = n.GetObjectValue<global::IcePanel.Api.Models.OrganizationUserInvite_landscapePermissions>(global::IcePanel.Api.Models.OrganizationUserInvite_landscapePermissions.CreateFromDiscriminatorValue); } },
                { "organizationId", n => { OrganizationId = n.GetStringValue(); } },
                { "permission", n => { Permission = n.GetEnumValue<global::IcePanel.Api.Models.PermissionType>(); } },
                { "revokedAt", n => { RevokedAt = n.GetDateTimeOffsetValue(); } },
                { "revokedBy", n => { RevokedBy = n.GetEnumValue<global::IcePanel.Api.Models.AuthType>(); } },
                { "revokedById", n => { RevokedById = n.GetStringValue(); } },
                { "usedAt", n => { UsedAt = n.GetDateTimeOffsetValue(); } },
                { "usedByUserId", n => { UsedByUserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteEnumValue<global::IcePanel.Api.Models.AuthType>("createdBy", CreatedBy);
            writer.WriteStringValue("createdById", CreatedById);
            writer.WriteStringValue("email", Email);
            writer.WriteDateTimeOffsetValue("expiresAt", ExpiresAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::IcePanel.Api.Models.OrganizationUserInvite_landscapePermissions>("landscapePermissions", LandscapePermissions);
            writer.WriteStringValue("organizationId", OrganizationId);
            writer.WriteEnumValue<global::IcePanel.Api.Models.PermissionType>("permission", Permission);
            writer.WriteDateTimeOffsetValue("revokedAt", RevokedAt);
            writer.WriteEnumValue<global::IcePanel.Api.Models.AuthType>("revokedBy", RevokedBy);
            writer.WriteStringValue("revokedById", RevokedById);
            writer.WriteDateTimeOffsetValue("usedAt", UsedAt);
            writer.WriteStringValue("usedByUserId", UsedByUserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
