// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OrganizationPlan
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "indie")]
        #pragma warning disable CS1591
        Indie,
        #pragma warning restore CS1591
        [EnumMember(Value = "pilot")]
        #pragma warning disable CS1591
        Pilot,
        #pragma warning restore CS1591
        [EnumMember(Value = "growth")]
        #pragma warning disable CS1591
        Growth,
        #pragma warning restore CS1591
        [EnumMember(Value = "scale")]
        #pragma warning disable CS1591
        Scale,
        #pragma warning restore CS1591
        [EnumMember(Value = "isolation")]
        #pragma warning disable CS1591
        Isolation,
        #pragma warning restore CS1591
    }
}
