// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrganizationPartial : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billingCurrency property</summary>
        public global::IcePanel.Api.Models.OrganizationBillingCurrency? BillingCurrency { get; set; }
        /// <summary>The billingCycle property</summary>
        public global::IcePanel.Api.Models.OrganizationBillingCycle? BillingCycle { get; set; }
        /// <summary>The billingEmail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingEmail { get; set; }
#nullable restore
#else
        public string BillingEmail { get; set; }
#endif
        /// <summary>The lineShapeDefault property</summary>
        public global::IcePanel.Api.Models.LineShape? LineShapeDefault { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The shareLinkAuthDomains property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ShareLinkAuthDomains { get; set; }
#nullable restore
#else
        public List<string> ShareLinkAuthDomains { get; set; }
#endif
        /// <summary>The shareLinksEnabled property</summary>
        public bool? ShareLinksEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.OrganizationPartial"/> and sets the default values.
        /// </summary>
        public OrganizationPartial()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.OrganizationPartial"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.OrganizationPartial CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.OrganizationPartial();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billingCurrency", n => { BillingCurrency = n.GetEnumValue<global::IcePanel.Api.Models.OrganizationBillingCurrency>(); } },
                { "billingCycle", n => { BillingCycle = n.GetEnumValue<global::IcePanel.Api.Models.OrganizationBillingCycle>(); } },
                { "billingEmail", n => { BillingEmail = n.GetStringValue(); } },
                { "lineShapeDefault", n => { LineShapeDefault = n.GetEnumValue<global::IcePanel.Api.Models.LineShape>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "shareLinkAuthDomains", n => { ShareLinkAuthDomains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "shareLinksEnabled", n => { ShareLinksEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::IcePanel.Api.Models.OrganizationBillingCurrency>("billingCurrency", BillingCurrency);
            writer.WriteEnumValue<global::IcePanel.Api.Models.OrganizationBillingCycle>("billingCycle", BillingCycle);
            writer.WriteStringValue("billingEmail", BillingEmail);
            writer.WriteEnumValue<global::IcePanel.Api.Models.LineShape>("lineShapeDefault", LineShapeDefault);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("shareLinkAuthDomains", ShareLinkAuthDomains);
            writer.WriteBoolValue("shareLinksEnabled", ShareLinksEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
