// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>
    /// An instance of a software system, running on a deployment node.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StructurizrSoftwareSystemInstance : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The deployment environment in which this software system instance resides (e.g. &quot;Development&quot;, &quot;Live&quot;, etc).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Environment { get; set; }
#nullable restore
#else
        public string Environment { get; set; }
#endif
        /// <summary>The set of HTTP-based health checks for this software system instance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IcePanel.Api.Models.StructurizrHttpHealthCheck>? HealthChecks { get; set; }
#nullable restore
#else
        public List<global::IcePanel.Api.Models.StructurizrHttpHealthCheck> HealthChecks { get; set; }
#endif
        /// <summary>The ID of this software system instance in the model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The number/index of this instance.</summary>
        public double? InstanceId { get; set; }
        /// <summary>The set of perspectives associated with this element.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IcePanel.Api.Models.StructurizrPerspective>? Perspectives { get; set; }
#nullable restore
#else
        public List<global::IcePanel.Api.Models.StructurizrPerspective> Perspectives { get; set; }
#endif
        /// <summary>A set of arbitrary name-value properties.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance_properties? Properties { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance_properties Properties { get; set; }
#endif
        /// <summary>The set of relationships from this software system instance to other elements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IcePanel.Api.Models.StructurizrRelationship>? Relationships { get; set; }
#nullable restore
#else
        public List<global::IcePanel.Api.Models.StructurizrRelationship> Relationships { get; set; }
#endif
        /// <summary>The ID of the software system this is an instance of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoftwareSystemId { get; set; }
#nullable restore
#else
        public string SoftwareSystemId { get; set; }
#endif
        /// <summary>A comma separated list of tags associated with this software system instance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tags { get; set; }
#nullable restore
#else
        public string Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance"/> and sets the default values.
        /// </summary>
        public StructurizrSoftwareSystemInstance()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "environment", n => { Environment = n.GetStringValue(); } },
                { "healthChecks", n => { HealthChecks = n.GetCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrHttpHealthCheck>(global::IcePanel.Api.Models.StructurizrHttpHealthCheck.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "instanceId", n => { InstanceId = n.GetDoubleValue(); } },
                { "perspectives", n => { Perspectives = n.GetCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrPerspective>(global::IcePanel.Api.Models.StructurizrPerspective.CreateFromDiscriminatorValue)?.AsList(); } },
                { "properties", n => { Properties = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance_properties>(global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance_properties.CreateFromDiscriminatorValue); } },
                { "relationships", n => { Relationships = n.GetCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrRelationship>(global::IcePanel.Api.Models.StructurizrRelationship.CreateFromDiscriminatorValue)?.AsList(); } },
                { "softwareSystemId", n => { SoftwareSystemId = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("environment", Environment);
            writer.WriteCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrHttpHealthCheck>("healthChecks", HealthChecks);
            writer.WriteStringValue("id", Id);
            writer.WriteDoubleValue("instanceId", InstanceId);
            writer.WriteCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrPerspective>("perspectives", Perspectives);
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrSoftwareSystemInstance_properties>("properties", Properties);
            writer.WriteCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrRelationship>("relationships", Relationships);
            writer.WriteStringValue("softwareSystemId", SoftwareSystemId);
            writer.WriteStringValue("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
