// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>The algorithm rank direction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StructurizrAutomaticLayout_rankDirection
    {
        [EnumMember(Value = "TopBottom")]
        #pragma warning disable CS1591
        TopBottom,
        #pragma warning restore CS1591
        [EnumMember(Value = "BottomTop")]
        #pragma warning disable CS1591
        BottomTop,
        #pragma warning restore CS1591
        [EnumMember(Value = "LeftRight")]
        #pragma warning disable CS1591
        LeftRight,
        #pragma warning restore CS1591
        [EnumMember(Value = "RightLeft")]
        #pragma warning disable CS1591
        RightLeft,
        #pragma warning restore CS1591
    }
}
