// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>
    /// A definition of a relationship style.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StructurizrRelationshipStyle : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The colour of the line, as a HTML RGB hex string (e.g. &apos;#ffffff&apos;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>A flag to indicate whether the line is rendered as dashed or not.</summary>
        public bool? Dashed { get; set; }
        /// <summary>The standard font size used to render the relationship annotation, in pixels.</summary>
        public double? FontSize { get; set; }
        /// <summary>The opacity used when rendering the line; 0-100.</summary>
        public double? Opacity { get; set; }
        /// <summary>The position of the annotation along the line; 0 (start) to 100 (end).</summary>
        public double? Position { get; set; }
        /// <summary>The routing algorithm used when rendering lines.</summary>
        public global::IcePanel.Api.Models.StructurizrRelationshipStyle_routing? Routing { get; set; }
        /// <summary>The tag to which this relationship style applies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>The thickness of the line, in pixels.</summary>
        public double? Thickness { get; set; }
        /// <summary>The width of the relationship annotation, in pixels.</summary>
        public double? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.StructurizrRelationshipStyle"/> and sets the default values.
        /// </summary>
        public StructurizrRelationshipStyle()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.StructurizrRelationshipStyle"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.StructurizrRelationshipStyle CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.StructurizrRelationshipStyle();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "color", n => { Color = n.GetStringValue(); } },
                { "dashed", n => { Dashed = n.GetBoolValue(); } },
                { "fontSize", n => { FontSize = n.GetDoubleValue(); } },
                { "opacity", n => { Opacity = n.GetDoubleValue(); } },
                { "position", n => { Position = n.GetDoubleValue(); } },
                { "routing", n => { Routing = n.GetEnumValue<global::IcePanel.Api.Models.StructurizrRelationshipStyle_routing>(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "thickness", n => { Thickness = n.GetDoubleValue(); } },
                { "width", n => { Width = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("color", Color);
            writer.WriteBoolValue("dashed", Dashed);
            writer.WriteDoubleValue("fontSize", FontSize);
            writer.WriteDoubleValue("opacity", Opacity);
            writer.WriteDoubleValue("position", Position);
            writer.WriteEnumValue<global::IcePanel.Api.Models.StructurizrRelationshipStyle_routing>("routing", Routing);
            writer.WriteStringValue("tag", Tag);
            writer.WriteDoubleValue("thickness", Thickness);
            writer.WriteDoubleValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
