// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>The visibility of the workspace</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StructurizrWorkspaceConfiguration_visibility
    {
        [EnumMember(Value = "Public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
        [EnumMember(Value = "Private")]
        #pragma warning disable CS1591
        Private,
        #pragma warning restore CS1591
    }
}
