// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>
    /// A system landscape view.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StructurizrSystemLandscapeView : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The set of animation steps (optional).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IcePanel.Api.Models.StructurizrAnimationStep>? Animations { get; set; }
#nullable restore
#else
        public List<global::IcePanel.Api.Models.StructurizrAnimationStep> Animations { get; set; }
#endif
        /// <summary>Represents the auto-layout configuration for a given view.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrAutomaticLayout? AutomaticLayout { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrAutomaticLayout AutomaticLayout { get; set; }
#endif
        /// <summary>The description of this view.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Represents a width and height pair.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrDimensions? Dimensions { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrDimensions Dimensions { get; set; }
#endif
        /// <summary>The set of elements in this views.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IcePanel.Api.Models.StructurizrElementView>? Elements { get; set; }
#nullable restore
#else
        public List<global::IcePanel.Api.Models.StructurizrElementView> Elements { get; set; }
#endif
        /// <summary>Specifies whether the enterprise boundary (to differentiate internal elements from external elements) should be visible on the resulting diagram.</summary>
        public bool? EnterpriseBoundaryVisible { get; set; }
        /// <summary>A unique identifier for this view.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>An integer representing the creation order of this view.</summary>
        public double? Order { get; set; }
        /// <summary>The paper size that should be used to render this view.</summary>
        public global::IcePanel.Api.Models.StructurizrSystemLandscapeView_paperSize? PaperSize { get; set; }
        /// <summary>A set of arbitrary name-value properties.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrSystemLandscapeView_properties? Properties { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrSystemLandscapeView_properties Properties { get; set; }
#endif
        /// <summary>The set of relationships in this views.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IcePanel.Api.Models.StructurizrRelationshipView>? Relationships { get; set; }
#nullable restore
#else
        public List<global::IcePanel.Api.Models.StructurizrRelationshipView> Relationships { get; set; }
#endif
        /// <summary>The title of this view (optional).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.StructurizrSystemLandscapeView"/> and sets the default values.
        /// </summary>
        public StructurizrSystemLandscapeView()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.StructurizrSystemLandscapeView"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.StructurizrSystemLandscapeView CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.StructurizrSystemLandscapeView();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "animations", n => { Animations = n.GetCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrAnimationStep>(global::IcePanel.Api.Models.StructurizrAnimationStep.CreateFromDiscriminatorValue)?.AsList(); } },
                { "automaticLayout", n => { AutomaticLayout = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrAutomaticLayout>(global::IcePanel.Api.Models.StructurizrAutomaticLayout.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "dimensions", n => { Dimensions = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrDimensions>(global::IcePanel.Api.Models.StructurizrDimensions.CreateFromDiscriminatorValue); } },
                { "elements", n => { Elements = n.GetCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrElementView>(global::IcePanel.Api.Models.StructurizrElementView.CreateFromDiscriminatorValue)?.AsList(); } },
                { "enterpriseBoundaryVisible", n => { EnterpriseBoundaryVisible = n.GetBoolValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "order", n => { Order = n.GetDoubleValue(); } },
                { "paperSize", n => { PaperSize = n.GetEnumValue<global::IcePanel.Api.Models.StructurizrSystemLandscapeView_paperSize>(); } },
                { "properties", n => { Properties = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrSystemLandscapeView_properties>(global::IcePanel.Api.Models.StructurizrSystemLandscapeView_properties.CreateFromDiscriminatorValue); } },
                { "relationships", n => { Relationships = n.GetCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrRelationshipView>(global::IcePanel.Api.Models.StructurizrRelationshipView.CreateFromDiscriminatorValue)?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrAnimationStep>("animations", Animations);
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrAutomaticLayout>("automaticLayout", AutomaticLayout);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrDimensions>("dimensions", Dimensions);
            writer.WriteCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrElementView>("elements", Elements);
            writer.WriteBoolValue("enterpriseBoundaryVisible", EnterpriseBoundaryVisible);
            writer.WriteStringValue("key", Key);
            writer.WriteDoubleValue("order", Order);
            writer.WriteEnumValue<global::IcePanel.Api.Models.StructurizrSystemLandscapeView_paperSize>("paperSize", PaperSize);
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrSystemLandscapeView_properties>("properties", Properties);
            writer.WriteCollectionOfObjectValues<global::IcePanel.Api.Models.StructurizrRelationshipView>("relationships", Relationships);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
