// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>
    /// The configuration associated with a set of views.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StructurizrConfiguration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A wrapper for the font and logo for diagram/documentation branding purposes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrBranding? Branding { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrBranding Branding { get; set; }
#endif
        /// <summary>The key of the view that should be shown by default.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultView { get; set; }
#nullable restore
#else
        public string DefaultView { get; set; }
#endif
        /// <summary>The key of the view that was saved most recently.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastSavedView { get; set; }
#nullable restore
#else
        public string LastSavedView { get; set; }
#endif
        /// <summary>The type of symbols to use when rendering metadata.</summary>
        public global::IcePanel.Api.Models.StructurizrConfiguration_metadataSymbols? MetadataSymbols { get; set; }
        /// <summary>A set of arbitrary name-value properties.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrConfiguration_properties? Properties { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrConfiguration_properties Properties { get; set; }
#endif
        /// <summary>The styles associated with this set of views.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrConfiguration_styles? Styles { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrConfiguration_styles Styles { get; set; }
#endif
        /// <summary>Provides a way for the terminology on diagrams, etc to be modified (e.g. language translations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrTerminology? Terminology { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrTerminology Terminology { get; set; }
#endif
        /// <summary>The URL(s) of the theme(s) to be used when rendering diagrams.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Themes { get; set; }
#nullable restore
#else
        public List<string> Themes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Models.StructurizrConfiguration"/> and sets the default values.
        /// </summary>
        public StructurizrConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.StructurizrConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.StructurizrConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Models.StructurizrConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "branding", n => { Branding = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrBranding>(global::IcePanel.Api.Models.StructurizrBranding.CreateFromDiscriminatorValue); } },
                { "defaultView", n => { DefaultView = n.GetStringValue(); } },
                { "lastSavedView", n => { LastSavedView = n.GetStringValue(); } },
                { "metadataSymbols", n => { MetadataSymbols = n.GetEnumValue<global::IcePanel.Api.Models.StructurizrConfiguration_metadataSymbols>(); } },
                { "properties", n => { Properties = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrConfiguration_properties>(global::IcePanel.Api.Models.StructurizrConfiguration_properties.CreateFromDiscriminatorValue); } },
                { "styles", n => { Styles = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrConfiguration_styles>(global::IcePanel.Api.Models.StructurizrConfiguration_styles.CreateFromDiscriminatorValue); } },
                { "terminology", n => { Terminology = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrTerminology>(global::IcePanel.Api.Models.StructurizrTerminology.CreateFromDiscriminatorValue); } },
                { "themes", n => { Themes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrBranding>("branding", Branding);
            writer.WriteStringValue("defaultView", DefaultView);
            writer.WriteStringValue("lastSavedView", LastSavedView);
            writer.WriteEnumValue<global::IcePanel.Api.Models.StructurizrConfiguration_metadataSymbols>("metadataSymbols", MetadataSymbols);
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrConfiguration_properties>("properties", Properties);
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrConfiguration_styles>("styles", Styles);
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrTerminology>("terminology", Terminology);
            writer.WriteCollectionOfPrimitiveValues<string>("themes", Themes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
