// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::IcePanel.Api.Models.SupportMessageBodyBug"/>, <see cref="global::IcePanel.Api.Models.SupportMessageBodyGeneral"/>, <see cref="global::IcePanel.Api.Models.SupportMessageBodyPartnerships"/>, <see cref="global::IcePanel.Api.Models.SupportMessageBodySales"/>, <see cref="global::IcePanel.Api.Models.SupportMessageBodySSOSamlRegistration"/>, <see cref="global::IcePanel.Api.Models.SupportMessageBodySupport"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SupportMessageBody : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.SupportMessageBodyBug"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.SupportMessageBodyBug? SupportMessageBodyBug { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.SupportMessageBodyBug SupportMessageBodyBug { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.SupportMessageBodyGeneral"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.SupportMessageBodyGeneral? SupportMessageBodyGeneral { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.SupportMessageBodyGeneral SupportMessageBodyGeneral { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.SupportMessageBodyPartnerships"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.SupportMessageBodyPartnerships? SupportMessageBodyPartnerships { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.SupportMessageBodyPartnerships SupportMessageBodyPartnerships { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.SupportMessageBodySales"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.SupportMessageBodySales? SupportMessageBodySales { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.SupportMessageBodySales SupportMessageBodySales { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.SupportMessageBodySSOSamlRegistration"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.SupportMessageBodySSOSamlRegistration? SupportMessageBodySSOSamlRegistration { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.SupportMessageBodySSOSamlRegistration SupportMessageBodySSOSamlRegistration { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IcePanel.Api.Models.SupportMessageBodySupport"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.SupportMessageBodySupport? SupportMessageBodySupport { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.SupportMessageBodySupport SupportMessageBodySupport { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Models.SupportMessageBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IcePanel.Api.Models.SupportMessageBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::IcePanel.Api.Models.SupportMessageBody();
            if("SupportMessageBodyBug".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SupportMessageBodyBug = new global::IcePanel.Api.Models.SupportMessageBodyBug();
            }
            else if("SupportMessageBodyGeneral".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SupportMessageBodyGeneral = new global::IcePanel.Api.Models.SupportMessageBodyGeneral();
            }
            else if("SupportMessageBodyPartnerships".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SupportMessageBodyPartnerships = new global::IcePanel.Api.Models.SupportMessageBodyPartnerships();
            }
            else if("SupportMessageBodySSOSamlRegistration".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SupportMessageBodySSOSamlRegistration = new global::IcePanel.Api.Models.SupportMessageBodySSOSamlRegistration();
            }
            else if("SupportMessageBodySales".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SupportMessageBodySales = new global::IcePanel.Api.Models.SupportMessageBodySales();
            }
            else if("SupportMessageBodySupport".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SupportMessageBodySupport = new global::IcePanel.Api.Models.SupportMessageBodySupport();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SupportMessageBodyBug != null)
            {
                return SupportMessageBodyBug.GetFieldDeserializers();
            }
            else if(SupportMessageBodyGeneral != null)
            {
                return SupportMessageBodyGeneral.GetFieldDeserializers();
            }
            else if(SupportMessageBodyPartnerships != null)
            {
                return SupportMessageBodyPartnerships.GetFieldDeserializers();
            }
            else if(SupportMessageBodySales != null)
            {
                return SupportMessageBodySales.GetFieldDeserializers();
            }
            else if(SupportMessageBodySSOSamlRegistration != null)
            {
                return SupportMessageBodySSOSamlRegistration.GetFieldDeserializers();
            }
            else if(SupportMessageBodySupport != null)
            {
                return SupportMessageBodySupport.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(SupportMessageBodyBug != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.SupportMessageBodyBug>(null, SupportMessageBodyBug);
            }
            else if(SupportMessageBodyGeneral != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.SupportMessageBodyGeneral>(null, SupportMessageBodyGeneral);
            }
            else if(SupportMessageBodyPartnerships != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.SupportMessageBodyPartnerships>(null, SupportMessageBodyPartnerships);
            }
            else if(SupportMessageBodySales != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.SupportMessageBodySales>(null, SupportMessageBodySales);
            }
            else if(SupportMessageBodySSOSamlRegistration != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.SupportMessageBodySSOSamlRegistration>(null, SupportMessageBodySSOSamlRegistration);
            }
            else if(SupportMessageBodySupport != null)
            {
                writer.WriteObjectValue<global::IcePanel.Api.Models.SupportMessageBodySupport>(null, SupportMessageBodySupport);
            }
        }
    }
}
#pragma warning restore CS0618
