// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.ShareLinks.Item.Landscape.Diagrams.Item.View;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IcePanel.Api.ShareLinks.Item.Landscape.Diagrams.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \share-links\{shortId}\landscape\diagrams\{diagramId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDiagramItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The view property</summary>
        public global::IcePanel.Api.ShareLinks.Item.Landscape.Diagrams.Item.View.ViewRequestBuilder View
        {
            get => new global::IcePanel.Api.ShareLinks.Item.Landscape.Diagrams.Item.View.ViewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.ShareLinks.Item.Landscape.Diagrams.Item.WithDiagramItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDiagramItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/share-links/{shortId}/landscape/diagrams/{diagramId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.ShareLinks.Item.Landscape.Diagrams.Item.WithDiagramItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDiagramItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/share-links/{shortId}/landscape/diagrams/{diagramId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
