// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IcePanel.Api.ShareLinks.Item.Options.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \share-links\{shortId}\options\{optionsShortId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOptionsShortItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOptionsShortItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/share-links/{shortId}/options/{optionsShortId}{?frameLocation*,inFrame*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOptionsShortItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/share-links/{shortId}/options/{optionsShortId}{?frameLocation*,inFrame*}", rawUrl)
        {
        }
        /// <summary>
        /// Find Options
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortGetResponse?> GetAsWithOptionsShortGetResponseAsync(Action<RequestConfiguration<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder.WithOptionsShortItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortGetResponse> GetAsWithOptionsShortGetResponseAsync(Action<RequestConfiguration<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder.WithOptionsShortItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortGetResponse>(requestInfo, global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find Options
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsWithOptionsShortGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortResponse?> GetAsync(Action<RequestConfiguration<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder.WithOptionsShortItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortResponse> GetAsync(Action<RequestConfiguration<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder.WithOptionsShortItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortResponse>(requestInfo, global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find Options
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder.WithOptionsShortItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder.WithOptionsShortItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Find Options
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithOptionsShortItemRequestBuilderGetQueryParameters 
        {
            [Obsolete("This property is deprecated, use FrameLocationAsShareLinkFrameLocation instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("frameLocation")]
            public string? FrameLocation { get; set; }
#nullable restore
#else
            [QueryParameter("frameLocation")]
            public string FrameLocation { get; set; }
#endif
            [QueryParameter("frameLocation")]
            public global::IcePanel.Api.Models.ShareLinkFrameLocation? FrameLocationAsShareLinkFrameLocation { get; set; }
            [QueryParameter("inFrame")]
            public bool? InFrame { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithOptionsShortItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::IcePanel.Api.ShareLinks.Item.Options.Item.WithOptionsShortItemRequestBuilder.WithOptionsShortItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
