// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Landscapes.Item.Versions.Item.Model.Objects.Item.Dependencies.Export;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IcePanel.Api.Landscapes.Item.Versions.Item.Model.Objects.Item.Dependencies
{
    /// <summary>
    /// Builds and executes requests for operations under \landscapes\{landscapeId}\versions\{versionId}\model\objects\{modelObjectId}\dependencies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DependenciesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The export property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Objects.Item.Dependencies.Export.ExportRequestBuilder Export
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Objects.Item.Dependencies.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Objects.Item.Dependencies.DependenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DependenciesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/model/objects/{modelObjectId}/dependencies", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Objects.Item.Dependencies.DependenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DependenciesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/model/objects/{modelObjectId}/dependencies", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
