// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies
{
    /// <summary>
    /// Builds and executes requests for operations under \landscapes\{landscapeId}\versions\{versionId}\model\dependencies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DependenciesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DependenciesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/model/dependencies?filter={filter}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DependenciesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/model/dependencies?filter={filter}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the incoming and outgoing dependencies for each requested object. Objects can be specified by ID or by label key-value pairs (or both): label pairs use OR semantics so an object matching any pair is included. Results are filtered by tags and/or technologies when provided: within each filter array the semantics are OR (any match passes), and between the two filter dimensions the semantics are AND (an object must satisfy both when both are specified).
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesGetResponse?> GetAsDependenciesGetResponseAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder.DependenciesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesGetResponse> GetAsDependenciesGetResponseAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder.DependenciesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesGetResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the incoming and outgoing dependencies for each requested object. Objects can be specified by ID or by label key-value pairs (or both): label pairs use OR semantics so an object matching any pair is included. Results are filtered by tags and/or technologies when provided: within each filter array the semantics are OR (any match passes), and between the two filter dimensions the semantics are AND (an object must satisfy both when both are specified).
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsDependenciesGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesResponse?> GetAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder.DependenciesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesResponse> GetAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder.DependenciesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the incoming and outgoing dependencies for each requested object. Objects can be specified by ID or by label key-value pairs (or both): label pairs use OR semantics so an object matching any pair is included. Results are filtered by tags and/or technologies when provided: within each filter array the semantics are OR (any match passes), and between the two filter dimensions the semantics are AND (an object must satisfy both when both are specified).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder.DependenciesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder.DependenciesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the incoming and outgoing dependencies for each requested object. Objects can be specified by ID or by label key-value pairs (or both): label pairs use OR semantics so an object matching any pair is included. Results are filtered by tags and/or technologies when provided: within each filter array the semantics are OR (any match passes), and between the two filter dimensions the semantics are AND (an object must satisfy both when both are specified).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DependenciesRequestBuilderGetQueryParameters 
        {
            /// <summary>Object selection and dependency filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DependenciesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Model.Dependencies.DependenciesRequestBuilder.DependenciesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
