// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Code;
using IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Mermaid;
using IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Text;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export
{
    /// <summary>
    /// Builds and executes requests for operations under \landscapes\{landscapeId}\versions\{versionId}\flows\{flowId}\export
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExportRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The code property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Code.CodeRequestBuilder Code
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Code.CodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mermaid property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Mermaid.MermaidRequestBuilder Mermaid
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Mermaid.MermaidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The text property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Text.TextRequestBuilder Text
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.Text.TextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.ExportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/flows/{flowId}/export", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.ExportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/flows/{flowId}/export", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
