// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Catalog.Suggestion.Brand;
using IcePanel.Api.Catalog.Suggestion.Information;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IcePanel.Api.Catalog.Suggestion
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\suggestion
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuggestionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The brand property</summary>
        public global::IcePanel.Api.Catalog.Suggestion.Brand.BrandRequestBuilder Brand
        {
            get => new global::IcePanel.Api.Catalog.Suggestion.Brand.BrandRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The information property</summary>
        public global::IcePanel.Api.Catalog.Suggestion.Information.InformationRequestBuilder Information
        {
            get => new global::IcePanel.Api.Catalog.Suggestion.Information.InformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Catalog.Suggestion.SuggestionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuggestionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/suggestion", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Catalog.Suggestion.SuggestionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuggestionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/suggestion", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
