// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IcePanel.Api.Organizations.Item.Landscapes
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LandscapesPostRequestBody : global::IcePanel.Api.Models.LandscapeRequired, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The parts of the format that&apos;s common to all versions/kinds of entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.BackstageEntityMap? BackstageEntities { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.BackstageEntityMap BackstageEntities { get; set; }
#endif
        /// <summary>Represents a Structurizr workspace, which is a wrapper for a software architecture model, views, and documentation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IcePanel.Api.Models.StructurizrWorkspace? StructurizrWorkspace { get; set; }
#nullable restore
#else
        public global::IcePanel.Api.Models.StructurizrWorkspace StructurizrWorkspace { get; set; }
#endif
        /// <summary>The templateId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateId { get; set; }
#nullable restore
#else
        public string TemplateId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Organizations.Item.Landscapes.LandscapesPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::IcePanel.Api.Organizations.Item.Landscapes.LandscapesPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IcePanel.Api.Organizations.Item.Landscapes.LandscapesPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "backstageEntities", n => { BackstageEntities = n.GetObjectValue<global::IcePanel.Api.Models.BackstageEntityMap>(global::IcePanel.Api.Models.BackstageEntityMap.CreateFromDiscriminatorValue); } },
                { "structurizrWorkspace", n => { StructurizrWorkspace = n.GetObjectValue<global::IcePanel.Api.Models.StructurizrWorkspace>(global::IcePanel.Api.Models.StructurizrWorkspace.CreateFromDiscriminatorValue); } },
                { "templateId", n => { TemplateId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::IcePanel.Api.Models.BackstageEntityMap>("backstageEntities", BackstageEntities);
            writer.WriteObjectValue<global::IcePanel.Api.Models.StructurizrWorkspace>("structurizrWorkspace", StructurizrWorkspace);
            writer.WriteStringValue("templateId", TemplateId);
        }
    }
}
#pragma warning restore CS0618
