// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content
{
    /// <summary>
    /// Builds and executes requests for operations under \landscapes\{landscapeId}\versions\{versionId}\diagrams\{diagramId}\content
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/diagrams/{diagramId}/content{?updateViewedAt*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/diagrams/{diagramId}/content{?updateViewedAt*}", rawUrl)
        {
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentGetResponse?> GetAsContentGetResponseAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentGetResponse> GetAsContentGetResponseAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentGetResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsContentGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse?> GetAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse> GetAsync(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPatchResponse?> PatchAsContentPatchResponseAsync(global::IcePanel.Api.Models.DiagramContentPartial body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPatchResponse> PatchAsContentPatchResponseAsync(global::IcePanel.Api.Models.DiagramContentPartial body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPatchResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PatchAsContentPatchResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse?> PatchAsync(global::IcePanel.Api.Models.DiagramContentPartial body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse> PatchAsync(global::IcePanel.Api.Models.DiagramContentPartial body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Replace
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPutResponse?> PutAsContentPutResponseAsync(global::IcePanel.Api.Models.DiagramContentRequired body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPutResponse> PutAsContentPutResponseAsync(global::IcePanel.Api.Models.DiagramContentRequired body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPutResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentPutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Replace
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PutAsContentPutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse?> PutAsync(global::IcePanel.Api.Models.DiagramContentRequired body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse> PutAsync(global::IcePanel.Api.Models.DiagramContentRequired body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::IcePanel.Api.Models.DiagramContentPartial body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::IcePanel.Api.Models.DiagramContentPartial body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Replace
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::IcePanel.Api.Models.DiagramContentRequired body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::IcePanel.Api.Models.DiagramContentRequired body, Action<RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Find
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContentRequestBuilderGetQueryParameters 
        {
            [QueryParameter("updateViewedAt")]
            public bool? UpdateViewedAt { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContentRequestBuilderGetRequestConfiguration : RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Update
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContentRequestBuilderPatchQueryParameters 
        {
            [QueryParameter("updateViewedAt")]
            public bool? UpdateViewedAt { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContentRequestBuilderPatchRequestConfiguration : RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPatchQueryParameters>
        {
        }
        /// <summary>
        /// Replace
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContentRequestBuilderPutQueryParameters 
        {
            [QueryParameter("updateViewedAt")]
            public bool? UpdateViewedAt { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContentRequestBuilderPutRequestConfiguration : RequestConfiguration<global::IcePanel.Api.Landscapes.Item.Versions.Item.Diagrams.Item.Content.ContentRequestBuilder.ContentRequestBuilderPutQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
