// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.LandscapeTemplates.Item.Thumbnails;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IcePanel.Api.LandscapeTemplates.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \landscape-templates\{landscapeTemplateId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLandscapeTemplateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The thumbnails property</summary>
        public global::IcePanel.Api.LandscapeTemplates.Item.Thumbnails.ThumbnailsRequestBuilder Thumbnails
        {
            get => new global::IcePanel.Api.LandscapeTemplates.Item.Thumbnails.ThumbnailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.LandscapeTemplates.Item.WithLandscapeTemplateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLandscapeTemplateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscape-templates/{landscapeTemplateId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.LandscapeTemplates.Item.WithLandscapeTemplateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLandscapeTemplateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscape-templates/{landscapeTemplateId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
