// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export;
using IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Thumbnail;
using IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.View;
using IcePanel.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \landscapes\{landscapeId}\versions\{versionId}\flows\{flowId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFlowItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The export property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.ExportRequestBuilder Export
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The thumbnail property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Thumbnail.ThumbnailRequestBuilder Thumbnail
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.Thumbnail.ThumbnailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The view property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.View.ViewRequestBuilder View
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.View.ViewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFlowItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/flows/{flowId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFlowItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/flows/{flowId}", rawUrl)
        {
        }
        /// <summary>
        /// Delete
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowDeleteResponse?> DeleteAsWithFlowDeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowDeleteResponse> DeleteAsWithFlowDeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowDeleteResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowDeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use DeleteAsWithFlowDeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowGetResponse?> GetAsWithFlowGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowGetResponse> GetAsWithFlowGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowGetResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsWithFlowGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Exists
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> HeadAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> HeadAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToHeadRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPatchResponse?> PatchAsWithFlowPatchResponseAsync(global::IcePanel.Api.Models.FlowPartial body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPatchResponse> PatchAsWithFlowPatchResponseAsync(global::IcePanel.Api.Models.FlowPartial body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPatchResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PatchAsWithFlowPatchResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse?> PatchAsync(global::IcePanel.Api.Models.FlowPartial body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse> PatchAsync(global::IcePanel.Api.Models.FlowPartial body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Upsert
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPutResponse?> PutAsWithFlowPutResponseAsync(global::IcePanel.Api.Models.FlowRequired body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPutResponse> PutAsWithFlowPutResponseAsync(global::IcePanel.Api.Models.FlowRequired body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPutResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowPutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Upsert
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PutAsWithFlowPutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse?> PutAsync(global::IcePanel.Api.Models.FlowRequired body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse> PutAsync(global::IcePanel.Api.Models.FlowRequired body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Exists
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToHeadRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToHeadRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.HEAD, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::IcePanel.Api.Models.FlowPartial body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::IcePanel.Api.Models.FlowPartial body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Upsert
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::IcePanel.Api.Models.FlowRequired body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::IcePanel.Api.Models.FlowRequired body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IcePanel.Api.Landscapes.Item.Versions.Item.Flows.Item.WithFlowItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFlowItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFlowItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFlowItemRequestBuilderHeadRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFlowItemRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFlowItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
