// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.Replies;
using IcePanel.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \landscapes\{landscapeId}\versions\{versionId}\comments\{commentId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCommentItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The replies property</summary>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.Replies.RepliesRequestBuilder Replies
        {
            get => new global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.Replies.RepliesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCommentItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/comments/{commentId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCommentItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/landscapes/{landscapeId}/versions/{versionId}/comments/{commentId}", rawUrl)
        {
        }
        /// <summary>
        /// Delete
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentDeleteResponse?> DeleteAsWithCommentDeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentDeleteResponse> DeleteAsWithCommentDeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentDeleteResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentDeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use DeleteAsWithCommentDeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentGetResponse?> GetAsWithCommentGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentGetResponse> GetAsWithCommentGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentGetResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsWithCommentGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPatchResponse?> PatchAsWithCommentPatchResponseAsync(global::IcePanel.Api.Models.CommentPartial body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPatchResponse> PatchAsWithCommentPatchResponseAsync(global::IcePanel.Api.Models.CommentPartial body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPatchResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PatchAsWithCommentPatchResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse?> PatchAsync(global::IcePanel.Api.Models.CommentPartial body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse> PatchAsync(global::IcePanel.Api.Models.CommentPartial body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Upsert
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutResponse?> PutAsWithCommentPutResponseAsync(global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutResponse> PutAsWithCommentPutResponseAsync(global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Upsert
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 422 status code</exception>
        /// <exception cref="global::IcePanel.Api.Models.Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PutAsWithCommentPutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse?> PutAsync(global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse> PutAsync(global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::IcePanel.Api.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse>(requestInfo, global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Find
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::IcePanel.Api.Models.CommentPartial body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::IcePanel.Api.Models.CommentPartial body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Upsert
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::IcePanel.Api.Landscapes.Item.Versions.Item.Comments.Item.WithCommentItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCommentItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCommentItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCommentItemRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCommentItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
