// <auto-generated/>
#pragma warning disable CS0618
using IcePanel.Api.Organizations.Item.BitbucketServer.Tokens;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IcePanel.Api.Organizations.Item.BitbucketServer
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{organizationId}\bitbucket-server
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BitbucketServerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The tokens property</summary>
        public global::IcePanel.Api.Organizations.Item.BitbucketServer.Tokens.TokensRequestBuilder Tokens
        {
            get => new global::IcePanel.Api.Organizations.Item.BitbucketServer.Tokens.TokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Organizations.Item.BitbucketServer.BitbucketServerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BitbucketServerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organizationId}/bitbucket-server", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IcePanel.Api.Organizations.Item.BitbucketServer.BitbucketServerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BitbucketServerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organizationId}/bitbucket-server", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
